config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :contacts
  get '/about' => 'pages#about'
  root 'pages#home'

end

app/models/concerns/contact.rb
class Contact < ActiveRecord::Base
   validates :name, presence: true
   validates :email, presence: true
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end
  
  def create
     @contact = Contact.new(contact_params)
     
     if @contact.save
        name = params[:contact][:name]
        email = params[:contact][:email]
        body = params[:contact][:comments]
        
        ContactMailer.contact_email(name, email, body).deliver
        
        flash[:success] = 'Message sent.'
        redirect_to new_contact_path
     else
        flash[:danger] = 'Error occured, message has not been sent.'
        redirect_to new_contact_path
     end
  end
   
   private
      def contact_params
         params.require(:contact).permit(:name, :email, :comments)
      end
end
   

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="well">
        <%= form_for @contact do |f| %>
            <div class="form-group">
                <%= f.label :name %>
                <%= f.text_field :name, class: 'form-control' %>
            </div>
            <div class="form-group">
                <%= f.label :email %>
                <%= f.email_field :email, class: 'form-control' %>
             </div>
            <div class="form-group">
                <%= f.label :comments %>
                <%= f.text_area :comments, class: 'form-control' %>
            </div>
        <%= f.submit 'Submit', class: 'btn btn-default' %>
        <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dev Match</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!-- <%= link_to root_path, class: 'navbar-brand' %> 
         <a class="navbar-brand" href="#">SaaS</a>Don't work command -->
          <%= link_to root_path, class: 'navbar-brand' do %>
              <i class="fa fa-users"></i>
              Dev Match
          <% end %>
                   
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"> <!-- <a href="/about">About Us --><span class="sr-only">(current)</span></li>
            <!-- <li><a href="#">Link</a></li> -->
            <!--<li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li> -->
          </ul>
          <form class="navbar-form navbar-right" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'About', about_path, class: 'navbar-brand' %></li>
            <li><%= link_to 'Contact Us', new_contact_path, class: 'navbar-brand' %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
<div class="container">
   <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: "alert alert-#{key}" %>
   <% end %>
<%= yield %>
</div>

</body>
</html>

app/views/pages/about.html.erb
<h2>About Us</h2>

app/views/pages/home.html.erb
<div class="jumbotron text-center">
  <h1>Welcome to Dev Match</h1>
  <h3>A membership site where entrepreneurs can meet developers</h3>
</div>